export const issueMockData = {
  status: "warning",
  name: 'Warning from typescript-estree when building TypeScript app',
  creator: 'John Doe',
  tags: [
    { id: '1', name: 'ts' },
    { id: '2', name: 'js' },
    { id: '3', name: 'scss' },
    { id: '4', name: 'confirmed' },
    // { id: '5', name: 'needs investigation' },
  ],
  participants: [
    { person: 'src/assets/people/person_2.jpg', id: 1 },
    { person: 'src/assets/people/person_2.jpg', id: 2 },
    { person: 'src/assets/people/person_2.jpg', id: 3 },
    { person: 'src/assets/people/person_2.jpg', id: 3 },
    { person: 'src/assets/people/person_2.jpg', id: 2 },
    { person: 'src/assets/people/person_2.jpg', id: 3 },
    { person: 'src/assets/people/person_2.jpg', id: 3 },
    { person: 'src/assets/people/person_2.jpg', id: 2 },
    { person: 'src/assets/people/person_2.jpg', id: 3 },
    { person: 'src/assets/people/person_2.jpg', id: 3 },
    { person: 'src/assets/people/person_2.jpg', id: 2 },
    { person: 'src/assets/people/person_2.jpg', id: 3 },
    { person: 'src/assets/people/person_2.jpg', id: 3 },
    { person: 'src/assets/people/person_2.jpg', id: 2 },
    { person: 'src/assets/people/person_2.jpg', id: 3 },
    { person: 'src/assets/people/person_2.jpg', id: 3 },
  ],
  comments: ['comment 1', 'comment 2', 'comment 3', 'comment 4', 'comment 5']
}